# Makefile para crear
# crear un script para crear los *.c a partir de los *.h
# eliminar los binarios
# touch
# quedaros con todos los ejecutables.-- desde todos los punto .c genera los .o y los metemos en una variable y pasa un solo ejecutable
# pagina manuel strip
CC = gcc
Objects = *.o
all:
	echo $*.
